# This tells Netlify where your site's main files (like index.html) are.
# "." means the root of your repository.
[build]
  publish = "."

[functions]
  directory = "netlify/functions/"
  # This gives your slotting function more time to run, preventing timeouts.
  timeout = 26
